### ISSUE TITLE
GitHub Copilot for Xcode: Can not login with enterprise license

### ISSUE THREAD

**Issue by aj-pilot** [github/CopilotForXcode#22]
GitHub Copilot for Xcode is not working in my enterprise setup. Every time I try to log in, I get this frustrating certificate error:

"Language server error: Server error: 1001 Could not log in with device flow on github.com: self-signed certificate in certificate chain nil"

I've attached a screenshot showing exactly what I'm seeing. I'm using:

GitHub Copilot for Xcode 0.27.92
![Screenshot 2024-11-04 at 20 00 00](https://github.com/user-attachments/assets/370b410c-426c-400a-9ef2-0c64aed00b6c)

**Comment by devm33** [comment]
Hi @aj-pilot, thanks for trying out Copilot for Xcode and sorry you're running into issues.

Could you share the proxy setup that you're using and what you have configured in the Advanced > Proxy settings for Copilot for Xcode?

See also:
- https://docs.github.com/en/copilot/managing-copilot/managing-github-copilot-in-your-organization/configuring-your-proxy-server-or-firewall-for-copilot
- https://docs.github.com/en/copilot/troubleshooting-github-copilot/troubleshooting-network-errors-for-github-copilot

**Comment by aj-pilot** [comment]
Hi @devm33 Thanks, for the quick reply. I am not using any proxy setup

**Comment by devm33** [comment]
Hi @aj-pilot, perhaps it's an enterprise VPN, firewall, or transparent/reverse proxy. Something is performing TLS inspection on the traffic from the extension. If that's not expected it may be a serious security issue ⚠ 

Ideally, you can either add the self-signed certificate to your system trust store or allow GitHub Copilot domains to bypass TLS inspection. See required domains here: [Configuring your proxy server or firewall for Copilot](https://docs.github.com/en/copilot/managing-copilot/managing-github-copilot-in-your-organization/configuring-your-proxy-server-or-firewall-for-copilot)

If neither of those are possible you can also disable certificate checking in the extension, though this is not recommended as it is less secure.

![Image](https://github.com/user-attachments/assets/de7c3da0-fd3f-437f-b9e6-01263ea5d13a)

**Comment by aj-pilot** [comment]
@devm33 Please find the attached logs and it is still exist in the latest pre-release too
[github-copilot-for-xcode.log](https://github.com/user-attachments/files/17625942/github-copilot-for-xcode.log)

**Comment by aj-pilot** [comment]
![Screenshot 2024-11-05 at 09 27 57](https://github.com/user-attachments/assets/4463bc9a-b64e-4810-8c18-4d56e0195711)
![Screenshot 2024-11-05 at 09 28 24](https://github.com/user-attachments/assets/cf8d0638-6f04-4195-a308-911ad57a9614)

**Comment by aj-pilot** [comment]
[github-copilot-for-xcode.log](https://github.com/user-attachments/files/17626736/github-copilot-for-xcode.log)

**Comment by devm33** [comment]
Thanks @aj-pilot, since you mentioned VS Code is working for you would you mind sharing the output of cmd+shift+p > GitHub Copilot: Collect Diagnostics

**Comment by aj-pilot** [comment]
@devm33 please find the attached output from the command
[Copilot.txt](https://github.com/user-attachments/files/17626954/Copilot.txt)
[Developer.txt](https://github.com/user-attachments/files/17626960/Developer.txt)

**Comment by pay-sean-me** [comment]
The same problem is occurring. I also have no problem with vscode, but i solved the problem there using `MAC CA VSCode Extension`

**Comment by aj-pilot** [comment]
@pay-sean-me so you just install that extension on VS Code?

**Comment by pay-sean-me** [comment]
@aj-pilot I think i wrote something incorrectly. i managed to fix in VSCode by installing an extension, but I'm still having the same issue in Xcode. sorry my bad english :)

**Comment by hoangtuanfithou** [comment]
I just want to chime in, I got the same issue as reported in [this ticket](https://github.com/github/CopilotForXcode/issues/18). Thank for reporting and I will following up here!

**Comment by devm33** [comment]
Hi all, I believe I found the issue here. If anyone would like to try this build: https://github.com/github/CopilotForXcode/releases/download/0.28.0/GitHubCopilotForXcode_proxyStrictSSL.dmg let me know if that fixes it for you 🤞

**Comment by pay-sean-me** [comment]
@devm33 Hi. my issue hasn't been resolved. :(

`Language server error: Server error: 1001 Could not log in with device flow on github.com: self-signed certificate in certificate chain nil`

**Comment by devm33** [comment]
@pay-sean-me could you install this build: https://github.com/github/CopilotForXcode/releases/download/0.28.0/GitHubCopilotForXcode_debugDiagnostics.dmg and then share the logs in `~/Library/Logs/GitHubCopilot/github-copilot-for-xcode.log`

**Comment by pay-sean-me** [comment]
@devm33 

[2024-11-10T23:23:43.690Z] [info] [GitHubCopilot] [68576] Starting language server in file:///Users/sean.me/Library/Application%20Support/com.github.CopilotForXcode/GitHub%20Copilot/support/, ["HOME": "/Users/sean.me", "GH_COPILOT_VERBOSE": "true"]
[2024-11-10T23:23:43.691Z] [info] [GitHubCopilot] [68576] Running on Xcode string("16.0"), extension version string("0.28.1011")
[2024-11-10T23:23:43.713Z] [info] [Client] [68576] Registering bridge launch agent
[2024-11-10T23:23:43.818Z] [info] [CommunicationBridge] [68582] Accepted new connection.
[2024-11-10T23:23:43.824Z] [info] [CommunicationBridge] [68582] Launching extension service app.
[2024-11-10T23:23:43.879Z] [info] [CommunicationBridge] [68582] Communication bridge started
[2024-11-10T23:23:44.024Z] [info] [CommunicationBridge] [68582] Finished launching extension service app.
[2024-11-10T23:23:44.123Z] [info] [Service] [68588] Syncing Xcode theme: Classic (Dark).xccolortheme
[2024-11-10T23:23:44.126Z] [info] [Service] [68588] Syncing Xcode theme: Default (Dark).xccolortheme
[2024-11-10T23:23:44.142Z] [info] [Service] [68588] XPC Service started.
[2024-11-10T23:23:44.142Z] [info] [CommunicationBridge] [68582] Accepted new connection.
[2024-11-10T23:23:44.227Z] [info] [GitHubCopilot] [68576] window/logMessage: {
  "message" : "[lsp] GitHub Copilot Language Server 1.243.0 initialized",
  "type" : 3
}
[2024-11-10T23:23:44.229Z] [info] [GitHubCopilot] [68576] window/logMessage: {
  "type" : 4,
  "message" : "[auth] Resetting copilot token"
}
[2024-11-10T23:23:44.229Z] [info] [GitHubCopilot] [68576] check status response: Response(status: Not Signed In, user: nil)
[2024-11-10T23:23:44.236Z] [info] [GitHubCopilot] [68576] window/logMessage: {
  "message" : "[auth] Resetting copilot token",
  "type" : 4
}
[2024-11-10T23:23:44.236Z] [info] [GitHubCopilot] [68576] check status response: Response(status: Not Signed In, user: nil)
[2024-11-10T23:23:44.345Z] [info] [GitHubCopilot] [68588] Starting language server in file:///Users/sean.me/Library/Application%20Support/com.github.CopilotForXcode/GitHub%20Copilot/support/, ["GH_COPILOT_VERBOSE": "true", "HOME": "/Users/sean.me"]
[2024-11-10T23:23:44.345Z] [info] [GitHubCopilot] [68588] Running on Xcode string("16.0"), extension version string("0.28.1011")
[2024-11-10T23:23:44.485Z] [info] [GitHubCopilot] [68576] window/logMessage: {
  "message" : "[certificates] Read 86 certificates from Mac keychain",
  "type" : 4
}
[2024-11-10T23:23:44.485Z] [info] [GitHubCopilot] [68576] window/logMessage: {
  "message" : "[certificates] Removed 19 expired certificates",
  "type" : 3
}
[2024-11-10T23:23:44.850Z] [info] [GitHubCopilot] [68588] window/logMessage: {
  "message" : "[lsp] GitHub Copilot Language Server 1.243.0 initialized",
  "type" : 3
}
[2024-11-10T23:23:44.853Z] [info] [GitHubCopilot] [68588] window/logMessage: {
  "type" : 4,
  "message" : "[auth] Resetting copilot token"
}
[2024-11-10T23:23:44.853Z] [info] [GitHubCopilot] [68588] check status response: Response(status: Not Signed In, user: nil)
[2024-11-10T23:23:44.861Z] [info] [GitHubCopilot] [68588] check status response: Response(status: Not Signed In, user: nil)
[2024-11-10T23:23:44.861Z] [info] [GitHubCopilot] [68588] window/logMessage: {
  "message" : "[auth] Resetting copilot token",
  "type" : 4
}
[2024-11-10T23:23:44.863Z] [info] [GitHubCopilot] [68588] Diagnostics:
[2024-11-10T23:23:46.057Z] [info] [GitHubCopilot] [68576] Diagnostics:
## Copilot

- Version: 1.243.0
- Build: prod
- Editor: Xcode/16.0

## Environment

- http_proxy: n/a
- https_proxy: n/a
- no_proxy: n/a
- SSL_CERT_FILE: n/a
- SSL_CERT_DIR: n/a
- OPENSSL_CONF: n/a

## Feature Flags



## Node setup

- Number of root certificates: 131
- Operating system: Darwin
- Operating system version: 23.6.0
- Operating system architecture: arm64
- NODE_OPTIONS: n/a
- NODE_EXTRA_CA_CERTS: n/a
- NODE_TLS_REJECT_UNAUTHORIZED: n/a
- tls default min version: TLSv1.2
- tls default max version: TLSv1.3

## Network Configuration

- Proxy host: n/a
- Proxy port: n/a
- Kerberos SPN: n/a
- Reject unauthorized: enabled
- Fetcher: HelixFetcher

## Reachability

- github.com: self-signed certificate in certificate chain
- api.github.com: HTTP 200 - OK
- copilot-proxy.githubusercontent.com: HTTP 200 - OK
- api.githubcopilot.com: HTTP 200 - OK
- copilot-telemetry.githubusercontent.com: HTTP 200 - OK
- default.exp-tas.com: HTTP 200 - OK
[2024-11-10T23:23:49.187Z] [info] [CommunicationBridge] [68582] Service app found: 68588 Optional("com.github.CopilotForXcode.ExtensionService")
[2024-11-10T23:23:49.187Z] [info] [CommunicationBridge] [68582] Service app is still valid
[2024-11-10T23:23:49.192Z] [info] [CommunicationBridge] [68582] Service app found: 68588 Optional("com.github.CopilotForXcode.ExtensionService")
[2024-11-10T23:23:49.192Z] [info] [CommunicationBridge] [68582] Service app is still valid
[2024-11-10T23:23:49.838Z] [info] [Service] [68588] Extension Service is not updated, no need to quit.
[2024-11-10T23:23:51.400Z] [info] [GitHubCopilot] [68576] window/logMessage: {
  "message" : "[auth] Resetting copilot token",
  "type" : 4
}
[2024-11-10T23:24:07.949Z] [info] [GitHubCopilot] [68576] window/logMessage: {
  "type" : 1,
  "message" : "[default] Error sending telemetry FetchError: self-signed certificate in certificate chain\n    at fetch (\/snapshot\/copilot-client\/node_modules\/@adobe\/helix-fetch\/src\/fetch\/index.js:99:11)\n    at processTicksAndRejections (node:internal\/process\/task_queues:95:5)\n    at cachingFetch (\/snapshot\/copilot-client\/node_modules\/@adobe\/helix-fetch\/src\/fetch\/index.js:288:16)\n    at Uge.fetch (\/snapshot\/copilot-client\/lib\/src\/network\/helix.ts:93:22) {\n  type: 'system',\n  _name: 'FetchError',\n  code: 'SELF_SIGNED_CERT_IN_CHAIN',\n  errno: undefined,\n  erroredSysCall: undefined\n}"
}
[2024-11-10T23:24:14.235Z] [info] [GitHubCopilot] [68576] check status response: Response(status: Not Signed In, user: nil)
[2024-11-10T23:24:14.235Z] [info] [GitHubCopilot] [68576] window/logMessage: {
  "type" : 4,
  "message" : "[auth] Resetting copilot token"
}
[2024-11-10T23:24:44.240Z] [info] [GitHubCopilot] [68576] window/logMessage: {
  "type" : 4,
  "message" : "[auth] Resetting copilot token"
}
[2024-11-10T23:24:44.241Z] [info] [GitHubCopilot] [68576] check status response: Response(status: Not Signed In, user: nil)
[2024-11-10T23:25:14.244Z] [info] [GitHubCopilot] [68576] check status response: Response(status: Not Signed In, user: nil)
[2024-11-10T23:25:14.244Z] [info] [GitHubCopilot] [68576] window/logMessage: {
  "type" : 4,
  "message" : "[auth] Resetting copilot token"
}
[2024-11-10T23:25:44.240Z] [info] [GitHubCopilot] [68576] window/logMessage: {
  "type" : 4,
  "message" : "[auth] Resetting copilot token"
}
[2024-11-10T23:25:44.242Z] [info] [GitHubCopilot] [68576] check status response: Response(status: Not Signed In, user: nil)
[2024-11-10T23:26:14.236Z] [info] [GitHubCopilot] [68576] window/logMessage: {
  "type" : 4,
  "message" : "[auth] Resetting copilot token"
}
[2024-11-10T23:26:14.237Z] [info] [GitHubCopilot] [68576] check status response: Response(status: Not Signed In, user: nil)
[2024-11-10T23:26:44.235Z] [info] [GitHubCopilot] [68576] window/logMessage: {
  "type" : 4,
  "message" : "[auth] Resetting copilot token"
}
[2024-11-10T23:26:44.235Z] [info] [GitHubCopilot] [68576] check status response: Response(status: Not Signed In, user: nil)
[2024-11-10T23:27:14.235Z] [info] [GitHubCopilot] [68576] window/logMessage: {
  "type" : 4,
  "message" : "[auth] Resetting copilot token"
}
[2024-11-10T23:27:14.236Z] [info] [GitHubCopilot] [68576] check status response: Response(status: Not Signed In, user: nil)
[2024-11-10T23:27:44.231Z] [info] [GitHubCopilot] [68576] window/logMessage: {
  "type" : 4,
  "message" : "[auth] Resetting copilot token"
}
[2024-11-10T23:27:44.231Z] [info] [GitHubCopilot] [68576] check status response: Response(status: Not Signed In, user: nil)
[2024-11-10T23:28:14.257Z] [info] [GitHubCopilot] [68576] check status response: Response(status: Not Signed In, user: nil)
[2024-11-10T23:28:14.256Z] [info] [GitHubCopilot] [68576] window/logMessage: {
  "message" : "[auth] Resetting copilot token",
  "type" : 4
}
[2024-11-10T23:28:44.231Z] [info] [GitHubCopilot] [68576] check status response: Response(status: Not Signed In, user: nil)
[2024-11-10T23:28:44.231Z] [info] [GitHubCopilot] [68576] window/logMessage: {
  "type" : 4,
  "message" : "[auth] Resetting copilot token"
}
[2024-11-10T23:29:14.234Z] [info] [GitHubCopilot] [68576] window/logMessage: {
  "type" : 4,
  "message" : "[auth] Resetting copilot token"
}
[2024-11-10T23:29:14.235Z] [info] [GitHubCopilot] [68576] check status response: Response(status: Not Signed In, user: nil)

**Comment by devm33** [comment]
@pay-sean-me thank you for sharing the diagnostics! It looks like there is TLS inspection happening specifically on the `github.com/login/` URL:

> github.com: self-signed certificate in certificate chain
api.github.com: HTTP 200 - OK
copilot-proxy.githubusercontent.com: HTTP 200 - OK
api.githubcopilot.com: HTTP 200 - OK
copilot-telemetry.githubusercontent.com: HTTP 200 - OK
default.exp-tas.com: HTTP 200 - OK

Is that expected?

**Comment by pay-sean-me** [comment]
@devm33 ah! i turned off the `Proxy strict SSL` setting and it connected! (using GitHubCopilotForXcode_proxyStrictSSL.dmg)

**Comment by devm33** [comment]
@pay-sean-me Great, thank you for confirming! That fix should be in the next release.

**Comment by devm33** [comment]
👋 This is out now in the latest [Pre-release 0.28.95](https://github.com/github/CopilotForXcode/releases/tag/0.28.95)

**Comment by built2order** [comment]
I'm testing the mass distribution of this app bundle in an enterprise environment. 

When a user attempts to leverage this capability, they are presented with the error "self-signed certificate in certificate chain". We leverage a zero trust based implementation (ie. agent steering traffic through Apple's NetworkExtension framework) and users do not have direct access to proxies, however all certificates are correctly installed on managed devices. Command line toolsets or package managers are able to use predefined ENV without error.

The ENV NODE_EXTRA_CA_CERTS is correctly set.

**Version**: 0.34.0

**Comment by testforstephen** [comment]
@built2order thanks for reaching out to us.

Duplicates with https://github.com/github/CopilotForXcode/issues/95. Xcode copilot currently does not respect `NODE_EXTRA_CA_CERTS` environment variable when starting itself. @yiqing-zhao let's pick up the OS's node cert env variable and configure it in copilot process.
